# # See https://pre-commit.com for more information
# default_language_version:
#     python: python3.10
# # See https://pre-commit.com/hooks.html for more hooks
exclude: |
    (?x)^(
        /requirements.txt|
        .*\/migrations\/.*
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast # simply checks whether the files parse as valid python.
      - id: check-json # checks json files for parseable syntax.
      - id: check-xml # checks xml files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: detect-private-key # detects the presence of private keys.
      - id: name-tests-test # verifies that test files are named correctly.
      - id: check-merge-conflict
      - id: trailing-whitespace # trims trailing whitespace.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: debug-statements
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      # - id: pretty-format-json # sets a standard for formatting json files.
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort # isort your imports, so you don't have to.
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black #  Black: The uncompromising Python code formatter
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8 # a command-line utility for enforcing style consistency across Python projects.
        additional_dependencies: [
            "flake8-bugbear", # finding likely bugs and design problems in your program
            "flake8-comprehensions", # plugin that helps you write better list/set/dict comprehensions.
            "flake8-mutable",
            "flake8-print", # check for Print statements in python files.
            "flake8-simplify", # plugin that helps you simplify your code.
          ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
    hooks:
      - id: commitizen
        stages:
          - commit-msg
